spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://ec2-13-209-158-233.ap-northeast-2.compute.amazonaws.com:3306/developdb?characterEncoding=UTF-8&serverTimezone=UTC
    username: umuser
    password: "#@!umuser"

  jpa:
    properties:
      hibernate:
        format_sql: true
        user_sql_comments: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug
      hibernate:
        SQL: debug