spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sgbo5003@gmail.com
    password: sepunnhyozyilpto
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true