spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: support@angkorchat.net
    password: K6A7C%5nq2R42uW!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true